[build]
  command = "npm install --force && npm run build"
  publish = "web-build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  CI = "false"
  EXPO_USE_WEBPACK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 