[build]
  command = "npm run build"
  publish = "web-build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 